environment:
  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      PYWEBVIEW_GUI: "cef"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      PYWEBVIEW_GUI: "cef"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
      PYWEBVIEW_GUI: "cef"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      PYWEBVIEW_GUI: "cef"

build: off

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  #- "pip install --disable-pip-version-check --user --upgrade pip"

  # Install the build dependencies of the project. If some dependencies contain
  # compiled extensions and are not provided as pre-built wheel packages,
  # pip will build them from source using the MSVC compiler matching the
  # target Python version and architecture
  - "%CMD_IN_ENV% pip install pytest==4.1.1 pythonnet six cefpython3==66.0"


test_script:
  # Run the project tests
  #- "%CMD_IN_ENV% python -m pytest tests -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_bg_color.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_evaluate_js.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_fullscreen.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_get_current_url.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_js_api.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_load_html.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_localization.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_min_size.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_multi_window.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_noresize.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_set_title.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_set_window_size.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_simple_browser.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_start.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_toggle_fullscreen.py -s"
  - "%CMD_IN_ENV% python -m pytest tests/test_url_load.py -s"

